### ISSUE TITLE
Array size assertion

### ISSUE THREAD

**Issue by xtwmx** [marcingrzejszczak/xmlassert#2]
Currently there is no way to easily assert the size of an array with XPathAssert.array("")

Workaround based on [count()](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/count) method I used:

```
private int getElementCount(String xpath, String xml) {
    XPath xPath = XPathFactory.newInstance().newXPath();
    try {
        return Integer.valueOf(xPath.evaluate("count(" + xpath + ")", new InputSource(new StringReader(xml))));
    } catch (XPathExpressionException e) {
        e.printStackTrace();
    }
    return -1;
}
```

The count method is also important to assert that a certain node has only 1 instance before moving forward in structure tree.
An ideal solution would be smth like this to satisfy both needs:

```
assertThat(xml1).node("some").hasCount(1).isEqualTo(0)
```

**Comment by marcingrzejszczak** [comment]
It's done and you can grab `0.0.2` from Central - http://repo2.maven.org/maven2/com/toomuchcoding/xmlassert/xmlassert/0.0.2/ . Sorry that you had to wait so long.
